# Generated by Django 4.1 on 2022-09-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postwall", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postwall",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
